name: brianwyrick
favicon: null
layout_spectrum: 0.79107
typography_spectrum: 0.2448723311536014
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ced1da'
    - '#0f0e16'
    - '#929196'
    - '#464449'
    - '#daa494'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
